#!/bin/sh

alias \
  mkdir="mkdir -pv" \
  ll="ls -l" \
  la="ls -la" \
  df="df -h" \
  du="du -ch"

# Colorize commands when possible (OSX)
ls -GFHh > /dev/null 2>&1 && alias \
  ls="ls -GFHh" \
  grep="grep --color=auto"

# Colorize commands when possible (Linux/BSD).
ls -hN --color=auto > /dev/null 2>&1 && alias \
  ls="ls -hN --color=auto --group-directories-first" \
  grep="grep --color=auto" \
  diff="diff --color=auto"

# Use eza instead of ls when possible
eza > /dev/null 2>&1 && alias \
  ls="eza --time-style=long-iso -g --group-directories-first" \
  tree="eza --tree"

# Use bat instead of cat if possible
bat --version > /dev/null 2>&1 && alias \
  cat="bat --pager=never --style=plain"

# custom programs
alias what-term="ps -p$PPID"
alias what-shell="ps -p $$"

# line count current directory
alias lc='rg --files  | xargs -d "\n" wc -l | perl -lne "\$s += \$1 if /(\d+) total/; END{print \$s}"'

alias dot="git -c status.showUntrackedFiles=no --git-dir=${DOTFILES_REPO} --work-tree=${HOME} -C ${HOME}"
alias ldot="lazygit --git-dir=$DOTFILES_REPO --work-tree=$HOME"

# Git log
# https://stackoverflow.com/a/34467298 <- other options
alias lg="git log --pretty='%C(Yellow)%h  %C(reset)%ad (%C(Green)%cr%C(reset))%x09 %C(Cyan)%an: %C(reset)%s' --graph --date=short --date-order"

# Useful aliases
alias mv="mv -v"

if command -v eza > /dev/null 2>&1; then
  alias ls="eza --classify"
  alias la="eza --all --all --sort=modified --classify"
  alias ll='eza --all --long --header --sort=modified --classify'
  alias lla='eza --all -all --long --header --group --sort=modified --classify'
  alias lt='eza --tree --level=15 --classify'
  alias llt='eza --tree --all --long --level=15 --classify'
fi

alias :GoToFile="nvim +GoToFile"
alias v="nvim +GoToFile"

alias sysd="sudo systemctl"
alias usysd="systemctl --user"
