#!/bin/sh

alias \
  mkdir="mkdir -pv" \
  ll="ls -l" \
  la="ls -la" \
  df="df -h" \
  du="du -ch"

# Colorize commands when possible (OSX)
ls -GFHh > /dev/null 2>&1 && alias \
  ls="ls -GFHh" \
  grep="grep --color=auto"

# Colorize commands when possible (Linux/BSD).
ls -hN --color=auto > /dev/null 2>&1 && alias \
  ls="ls -hN --color=auto --group-directories-first" \
  grep="grep --color=auto" \
  diff="diff --color=auto"

# Use exa instead of ls when possible
exa > /dev/null 2>&1 && alias \
  ls="exa --time-style=long-iso -g --group-directories-first" \
  tree="exa --tree"

# Use bat instead of cat if possible
bat --version > /dev/null 2>&1 && alias \
  cat="bat --pager=never --style=plain"

# custom programs
alias what-term="ps -p$PPID"
alias what-shell="ps -p $$"

# line count current directory
alias lc='rg --files  | xargs -d "\n" wc -l | perl -lne "\$s += \$1 if /(\d+) total/; END{print \$s}"'

alias yadm='$HOME/bin/yadm --yadm-repo $YADM_REPO'
alias dot='$HOME/bin/yadm --yadm-repo $YADM_REPO'

# Git log
alias lg="git log --pretty='%C(Yellow)%h  %C(reset)%ad (%C(Green)%cr%C(reset))%x09 %C(Cyan)%an: %C(reset)%s' --graph --date=short --date-order"

# Useful aliases
alias mv="mv -v"
alias cp="cp -v"

if command -v btm > /dev/null 2>&1; then
  alias htop="btm"
  alias top="btm"
fi

if command -v fd > /dev/null 2>&1; then
  alias find="fd"
fi

if command -v exa > /dev/null 2>&1; then
  alias ls="exa --classify"
  alias la="exa --all --all --sort=modified --classify"
  alias ll='exa --all --long --header --sort=modified --classify'
  alias lla='exa --all -all --long --header --group --sort=modified --classify'
  alias lt='exa --tree --level=15 --classify'
  alias llt='exa --tree --all --long --level=15 --classify'
fi

alias :GoToFile="nvim +GoToFile"
