# Migrated from 0.55.1 config -> 0.60.0 compatible
gui:
  nerdFontsVersion: "3"
  scrollHeight: 20
  scrollPastBottom: true
  showFileTree: false
  showListFooter: false
  showRandomTip: true
  showCommandLog: true
  showBottomLine: false
  commandLogSize: 8
  splitDiff: auto
  theme:
    lightTheme: false
    activeBorderColor:
      - red
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - white
    selectedLineBgColor:
      - black
    selectedRangeBgColor:
      - yellow
    cherryPickedCommitBgColor:
      - blue
    cherryPickedCommitFgColor:
      - cyan
    unstagedChangesColor:
      - white
  commitLength:
    show: true
  authorColors:
    'Hassaan Khan': '#ff0000'
    'hqkhan': '#ff0000'
git:
  pagers:
    - useConfig: false
      colorArg: always
      pager: delta --dark --paging=never
  merging:
    manualCommit: false
    args: ''
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  branchLogCmd: "git log --pretty='%C(Yellow)%h  %C(reset)%ad (%C(Green)%cr%C(reset))%x09 %C(Cyan)%an: %C(reset)%s' --graph --date=short --date-order {{branchName}}"
  overrideGpg: false
  disableForcePushing: true
  parseEmoji: true
  log:
    order: 'topo-order'
    showGraph: 'always'
    showWholeGraph: false
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium
os:
  editPreset: 'nvim'
  copyToClipboardCmd: printf "\033]52;c;$(printf {{text}} | base64)\a" > /dev/tty
refresher:
  refreshInterval: 10
  fetchInterval: 60
update:
  method: prompt
  days: 14
confirmOnQuit: false
quitOnTopLevelReturn: true
disableStartupPopups: false
notARepository: 'quit'
promptToReturnFromSubprocess: false
keybinding:
  universal:
    quit: 'q'
    quit-alt1: '<c-c>'
    return: '<esc>'
    quitWithoutChangingDirectory: 'Q'
    togglePanel: '<tab>'
    prevItem: '<up>'
    nextItem: '<down>'
    prevItem-alt: 'k'
    nextItem-alt: 'j'
    prevPage: ','
    nextPage: '.'
    gotoTop: '<'
    gotoBottom: '>'
    prevBlock: '<left>'
    nextBlock: '<right>'
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    jumpToBlock: ["1", "2", "3", "4", "5"]
    nextMatch: 'n'
    prevMatch: 'N'
    optionMenu-alt1: '?'
    select: '<space>'
    goInto: '<enter>'
    openRecentRepos: '<c-r>'
    confirm: '<enter>'
    remove: 'd'
    new: 'n'
    edit: 'e'
    openFile: 'o'
    scrollUpMain: '<pgup>'
    scrollDownMain: '<pgdown>'
    scrollUpMain-alt1: 'K'
    scrollDownMain-alt1: 'J'
    scrollUpMain-alt2: '<c-u>'
    scrollDownMain-alt2: '<c-d>'
    executeShellCommand: ':'
    createRebaseOptionsMenu: 'm'
    pushFiles: 'P'
    pullFiles: 'p'
    refresh: 'R'
    createPatchOptionsMenu: '<c-p>'
    nextTab: ']'
    prevTab: '['
    nextScreenMode: '+'
    prevScreenMode: '_'
    undo: 'z'
    redo: 'Z'
    filteringMenu: '<c-s>'
    diffingMenu: 'W'
    diffingMenu-alt: '<c-e>'
    copyToClipboard: '<c-o>'
    extrasMenu: '@'
    toggleWhitespaceInDiffView: '<c-w>'
  status:
    checkForUpdate: 'u'
    recentRepos: '<enter>'
  files:
    commitChangesWithoutHook: 'w'
    amendLastCommit: 'A'
    commitChangesWithEditor: 'C'
    ignoreFile: 'i'
    refreshFiles: 'r'
    stashAllChanges: 's'
    viewStashOptions: 'S'
    toggleStagedAll: 'a'
    viewResetOptions: 'D'
    fetch: 'f'
    toggleTreeView: '`'
  branches:
    createPullRequest: 'o'
    viewPullRequestOptions: 'O'
    checkoutBranchByName: 'c'
    forceCheckoutBranch: 'F'
    rebaseBranch: 'r'
    mergeIntoCurrentBranch: 'M'
    viewGitFlowOptions: 'i'
    fastForward: 'f'
    pushTag: 'P'
    setUpstream: 'u'
    fetchRemote: 'f'
  commits:
    squashDown: 's'
    renameCommit: 'r'
    renameCommitWithEditor: 'R'
    viewResetOptions: 'g'
    markCommitAsFixup: 'f'
    createFixupCommit: 'F'
    squashAboveCommits: 'S'
    moveDownCommit: '<c-j>'
    moveUpCommit: '<c-k>'
    amendToCommit: 'A'
    pickCommit: 'p'
    revertCommit: 't'
    cherryPickCopy: 'C'
    pasteCommits: 'V'
    tagCommit: 'T'
    checkoutCommit: '<space>'
    resetCherryPick: '<c-R>'
    copyCommitAttributeToClipboard: 'y'
  stash:
    popStash: 'g'
  commitFiles:
    checkoutCommitFile: 'c'
  main:
    toggleSelectHunk: 'a'
    pickBothHunks: 'b'
  submodules:
    init: 'i'
    update: 'u'
    bulkMenu: 'b'
