[misc]
# Disable specific steps - same options as the command line flag
disable = ["ruby_gems", "gem", "tlmgr", "node", "gnome_shell_extensions", "containers", "toolbx"]

# List of remote machines with Topgrade installed on them
# ARM box, AL2 x86 box
remote_topgrades = ["hqkhan-ec.aka.corp.amazon.com"]
remote_topgrade_path = ".cargo/bin/topgrade"

# Cleanup temporary or old files
cleanup = true

# Commands to run before anything
[pre_commands]
"Auth" = "pkill ssh & mwinit -s --aea && ssh-add"

# Custom commands
[commands]
"Toolbox" = "toolbox update"
"Brazil Cache Clean" = "brazil-package-cache clean"
"WSSH" = "wssh update"
